[mqtt_broker]
host = "localhost"
port = "1883"
vda_interface = "uagv"

[vehicle]
serial_number = "s23"
manufacturer = "rikeb"
vda_version = "v2"
vda_full_version = "2.0.0"

[settings]
state_frequency = 1.0
visualization_frequency = 5.0 
action_time = 1.0
speed = 0.2